EXEMPLO MARVEL
CREATE TABLE HEROIS{
ID INT PRIMARY KEY,
NOME VARCHAR(50),
PODER VARCHAR (50),
AFILIAÇÃO VARCHAR(50)    
}

INSERT INTO HEROIS FROM (1, "BATMAN","RIQUEZA","MARVEL");
SELECT NOME FROM HEROIS WHERE "BATMAN"